// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: reminder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      string                 `protobuf:"bytes,4,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReminderRequest) Reset() {
	*x = CreateReminderRequest{}
	mi := &file_reminder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRequest) ProtoMessage() {}

func (x *CreateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReminderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReminderRequest) GetRemindAt() string {
	if x != nil {
		return x.RemindAt
	}
	return ""
}

type GetRemindersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "sent", or empty for all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemindersRequest) Reset() {
	*x = GetRemindersRequest{}
	mi := &file_reminder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemindersRequest) ProtoMessage() {}

func (x *GetRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemindersRequest.ProtoReflect.Descriptor instead.
func (*GetRemindersRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{1}
}

func (x *GetRemindersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRemindersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderRequest) Reset() {
	*x = GetReminderRequest{}
	mi := &file_reminder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderRequest) ProtoMessage() {}

func (x *GetReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderRequest.ProtoReflect.Descriptor instead.
func (*GetReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{2}
}

func (x *GetReminderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetReminderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      string                 `protobuf:"bytes,5,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReminderRequest) Reset() {
	*x = UpdateReminderRequest{}
	mi := &file_reminder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderRequest) ProtoMessage() {}

func (x *UpdateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderRequest.ProtoReflect.Descriptor instead.
func (*UpdateReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReminderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReminderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateReminderRequest) GetRemindAt() string {
	if x != nil {
		return x.RemindAt
	}
	return ""
}

type DeleteReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReminderRequest) Reset() {
	*x = DeleteReminderRequest{}
	mi := &file_reminder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderRequest) ProtoMessage() {}

func (x *DeleteReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderRequest.ProtoReflect.Descriptor instead.
func (*DeleteReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReminderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteReminderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      string                 `protobuf:"bytes,5,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	IsSent        bool                   `protobuf:"varint,6,opt,name=is_sent,json=isSent,proto3" json:"is_sent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReminderResponse) Reset() {
	*x = ReminderResponse{}
	mi := &file_reminder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderResponse) ProtoMessage() {}

func (x *ReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderResponse.ProtoReflect.Descriptor instead.
func (*ReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{5}
}

func (x *ReminderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReminderResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReminderResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReminderResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReminderResponse) GetRemindAt() string {
	if x != nil {
		return x.RemindAt
	}
	return ""
}

func (x *ReminderResponse) GetIsSent() bool {
	if x != nil {
		return x.IsSent
	}
	return false
}

func (x *ReminderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReminderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRemindersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reminders     []*ReminderResponse    `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemindersResponse) Reset() {
	*x = GetRemindersResponse{}
	mi := &file_reminder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemindersResponse) ProtoMessage() {}

func (x *GetRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemindersResponse.ProtoReflect.Descriptor instead.
func (*GetRemindersResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{6}
}

func (x *GetRemindersResponse) GetReminders() []*ReminderResponse {
	if x != nil {
		return x.Reminders
	}
	return nil
}

type DeleteReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReminderResponse) Reset() {
	*x = DeleteReminderResponse{}
	mi := &file_reminder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderResponse) ProtoMessage() {}

func (x *DeleteReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderResponse.ProtoReflect.Descriptor instead.
func (*DeleteReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteReminderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_reminder_proto protoreflect.FileDescriptor

const file_reminder_proto_rawDesc = "" +
	"\n" +
	"\x0ereminder.proto\x12\breminder\"\x85\x01\n" +
	"\x15CreateReminderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tremind_at\x18\x04 \x01(\tR\bremindAt\"F\n" +
	"\x13GetRemindersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"=\n" +
	"\x12GetReminderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x95\x01\n" +
	"\x15UpdateReminderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tremind_at\x18\x05 \x01(\tR\bremindAt\"@\n" +
	"\x15DeleteReminderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\xe7\x01\n" +
	"\x10ReminderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tremind_at\x18\x05 \x01(\tR\bremindAt\x12\x17\n" +
	"\ais_sent\x18\x06 \x01(\bR\x06isSent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"P\n" +
	"\x14GetRemindersResponse\x128\n" +
	"\treminders\x18\x01 \x03(\v2\x1a.reminder.ReminderResponseR\treminders\"L\n" +
	"\x16DeleteReminderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x03\n" +
	"\x0fReminderService\x12M\n" +
	"\x0eCreateReminder\x12\x1f.reminder.CreateReminderRequest\x1a\x1a.reminder.ReminderResponse\x12M\n" +
	"\fGetReminders\x12\x1d.reminder.GetRemindersRequest\x1a\x1e.reminder.GetRemindersResponse\x12G\n" +
	"\vGetReminder\x12\x1c.reminder.GetReminderRequest\x1a\x1a.reminder.ReminderResponse\x12M\n" +
	"\x0eUpdateReminder\x12\x1f.reminder.UpdateReminderRequest\x1a\x1a.reminder.ReminderResponse\x12S\n" +
	"\x0eDeleteReminder\x12\x1f.reminder.DeleteReminderRequest\x1a .reminder.DeleteReminderResponseB:Z8github.com/kiribu/jwt-practice/internal/reminder/grpc/pbb\x06proto3"

var (
	file_reminder_proto_rawDescOnce sync.Once
	file_reminder_proto_rawDescData []byte
)

func file_reminder_proto_rawDescGZIP() []byte {
	file_reminder_proto_rawDescOnce.Do(func() {
		file_reminder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)))
	})
	return file_reminder_proto_rawDescData
}

var file_reminder_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_reminder_proto_goTypes = []any{
	(*CreateReminderRequest)(nil),  // 0: reminder.CreateReminderRequest
	(*GetRemindersRequest)(nil),    // 1: reminder.GetRemindersRequest
	(*GetReminderRequest)(nil),     // 2: reminder.GetReminderRequest
	(*UpdateReminderRequest)(nil),  // 3: reminder.UpdateReminderRequest
	(*DeleteReminderRequest)(nil),  // 4: reminder.DeleteReminderRequest
	(*ReminderResponse)(nil),       // 5: reminder.ReminderResponse
	(*GetRemindersResponse)(nil),   // 6: reminder.GetRemindersResponse
	(*DeleteReminderResponse)(nil), // 7: reminder.DeleteReminderResponse
}
var file_reminder_proto_depIdxs = []int32{
	5, // 0: reminder.GetRemindersResponse.reminders:type_name -> reminder.ReminderResponse
	0, // 1: reminder.ReminderService.CreateReminder:input_type -> reminder.CreateReminderRequest
	1, // 2: reminder.ReminderService.GetReminders:input_type -> reminder.GetRemindersRequest
	2, // 3: reminder.ReminderService.GetReminder:input_type -> reminder.GetReminderRequest
	3, // 4: reminder.ReminderService.UpdateReminder:input_type -> reminder.UpdateReminderRequest
	4, // 5: reminder.ReminderService.DeleteReminder:input_type -> reminder.DeleteReminderRequest
	5, // 6: reminder.ReminderService.CreateReminder:output_type -> reminder.ReminderResponse
	6, // 7: reminder.ReminderService.GetReminders:output_type -> reminder.GetRemindersResponse
	5, // 8: reminder.ReminderService.GetReminder:output_type -> reminder.ReminderResponse
	5, // 9: reminder.ReminderService.UpdateReminder:output_type -> reminder.ReminderResponse
	7, // 10: reminder.ReminderService.DeleteReminder:output_type -> reminder.DeleteReminderResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reminder_proto_init() }
func file_reminder_proto_init() {
	if File_reminder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminder_proto_goTypes,
		DependencyIndexes: file_reminder_proto_depIdxs,
		MessageInfos:      file_reminder_proto_msgTypes,
	}.Build()
	File_reminder_proto = out.File
	file_reminder_proto_goTypes = nil
	file_reminder_proto_depIdxs = nil
}
