// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserStatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserStatsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalRemindersCreated   int64                  `protobuf:"varint,2,opt,name=total_reminders_created,json=totalRemindersCreated,proto3" json:"total_reminders_created,omitempty"`
	TotalRemindersCompleted int64                  `protobuf:"varint,3,opt,name=total_reminders_completed,json=totalRemindersCompleted,proto3" json:"total_reminders_completed,omitempty"`
	TotalRemindersDeleted   int64                  `protobuf:"varint,4,opt,name=total_reminders_deleted,json=totalRemindersDeleted,proto3" json:"total_reminders_deleted,omitempty"`
	ActiveReminders         int64                  `protobuf:"varint,5,opt,name=active_reminders,json=activeReminders,proto3" json:"active_reminders,omitempty"`
	CompletionRate          float64                `protobuf:"fixed64,6,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	FirstReminderAt         string                 `protobuf:"bytes,7,opt,name=first_reminder_at,json=firstReminderAt,proto3" json:"first_reminder_at,omitempty"`
	LastActivityAt          string                 `protobuf:"bytes,8,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStatsResponse) GetTotalRemindersCreated() int64 {
	if x != nil {
		return x.TotalRemindersCreated
	}
	return 0
}

func (x *UserStatsResponse) GetTotalRemindersCompleted() int64 {
	if x != nil {
		return x.TotalRemindersCompleted
	}
	return 0
}

func (x *UserStatsResponse) GetTotalRemindersDeleted() int64 {
	if x != nil {
		return x.TotalRemindersDeleted
	}
	return 0
}

func (x *UserStatsResponse) GetActiveReminders() int64 {
	if x != nil {
		return x.ActiveReminders
	}
	return 0
}

func (x *UserStatsResponse) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *UserStatsResponse) GetFirstReminderAt() string {
	if x != nil {
		return x.FirstReminderAt
	}
	return ""
}

func (x *UserStatsResponse) GetLastActivityAt() string {
	if x != nil {
		return x.LastActivityAt
	}
	return ""
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\tanalytics\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x82\x03\n" +
	"\x11UserStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x126\n" +
	"\x17total_reminders_created\x18\x02 \x01(\x03R\x15totalRemindersCreated\x12:\n" +
	"\x19total_reminders_completed\x18\x03 \x01(\x03R\x17totalRemindersCompleted\x126\n" +
	"\x17total_reminders_deleted\x18\x04 \x01(\x03R\x15totalRemindersDeleted\x12)\n" +
	"\x10active_reminders\x18\x05 \x01(\x03R\x0factiveReminders\x12'\n" +
	"\x0fcompletion_rate\x18\x06 \x01(\x01R\x0ecompletionRate\x12*\n" +
	"\x11first_reminder_at\x18\a \x01(\tR\x0ffirstReminderAt\x12(\n" +
	"\x10last_activity_at\x18\b \x01(\tR\x0elastActivityAt2`\n" +
	"\x10AnalyticsService\x12L\n" +
	"\fGetUserStats\x12\x1e.analytics.GetUserStatsRequest\x1a\x1c.analytics.UserStatsResponseB;Z9github.com/kiribu/jwt-practice/internal/analytics/grpc/pbb\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analytics_proto_goTypes = []any{
	(*GetUserStatsRequest)(nil), // 0: analytics.GetUserStatsRequest
	(*UserStatsResponse)(nil),   // 1: analytics.UserStatsResponse
}
var file_proto_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetUserStats:input_type -> analytics.GetUserStatsRequest
	1, // 1: analytics.AnalyticsService.GetUserStats:output_type -> analytics.UserStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
